services:
  # Serviço para o banco de dados PostgreSQL
  db:
    image: postgres:latest
    container_name: rpg-postgres
    #restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  # Serviço para o banco de dados MongoDB
  mongodb:
    image: mongo:latest
    container_name: rpg-mongodb
    #restart: always
    volumes:
      - ./data/mongodb:/data/db
    ports:
      - "27017:27017"

  # Serviço para o seu backend em Rust
  backend:
    build:
      context: . 
      dockerfile: .\backend\Dockerfile
    container_name: rpg-backend
    #restart: always
    depends_on:
      - db
      - mongodb
    ports:
      - "8000:8000"
    volumes:
      - .:/app